"""create core schema

Revision ID: 650ea4a2ebd5
Revises: 
Create Date: 2026-07-23 04:25:35.011109

"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.services.partitioning import create_partition_sql

# revision identifiers, used by Alembic.
revision: str = '650ea4a2ebd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('driver_key', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('management_ip', postgresql.INET(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('device_type_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('os_variant', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), server_default='300', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('raw_facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_devices_device_type_id', 'devices', ['device_type_id'], unique=False)
    op.create_index('ix_devices_is_active', 'devices', ['is_active'], unique=False)
    op.create_index('ix_devices_management_ip', 'devices', ['management_ip'], unique=False)
    op.create_index('ix_devices_raw_facts', 'devices', ['raw_facts'], unique=False, postgresql_using='gin')
    op.create_index('ix_devices_vendor_id', 'devices', ['vendor_id'], unique=False)
    op.create_table('device_capabilities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('capability_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'capability_id', name='uq_device_capabilities_device_capability')
    )
    op.create_index('ix_device_capabilities_capability_id', 'device_capabilities', ['capability_id'], unique=False)
    op.create_index('ix_device_capabilities_device_id', 'device_capabilities', ['device_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('interfaces',
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('interface_type', sa.String(length=50), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('speed_mbps', sa.BigInteger(), nullable=True),
    sa.Column('admin_status', sa.String(length=20), nullable=True),
    sa.Column('oper_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_interfaces_device_name')
    )
    op.create_index('ix_interfaces_device_id', 'interfaces', ['device_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_device_id', 'job_runs', ['device_id'], unique=False)
    op.create_index('ix_job_runs_started_at', 'job_runs', ['started_at'], unique=False)
    op.create_index('ix_job_runs_status', 'job_runs', ['status'], unique=False)
    op.create_table('interface_metrics',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interface_id', sa.BigInteger(), nullable=False),
    sa.Column('octets_in', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('octets_out', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('errors_in', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('errors_out', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('discards_in', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('discards_out', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at'),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    op.create_index('ix_interface_metrics_interface_id', 'interface_metrics', ['interface_id'], unique=False)
    op.create_index('ix_interface_metrics_recorded_at', 'interface_metrics', ['recorded_at'], unique=False)

    # Partisi awal: bulan berjalan + bulan berikutnya, supaya siap menerima data
    # segera setelah migrasi ini selesai. Partisi bulan-bulan selanjutnya dibuat
    # lewat app.services.partitioning (dipanggil oleh task terjadwal di masa depan).
    now = datetime.now(UTC)
    for offset in (0, 1):
        year = now.year + (now.month - 1 + offset) // 12
        month = (now.month - 1 + offset) % 12 + 1
        op.execute(create_partition_sql('interface_metrics', year, month))

    op.create_table('neighbors',
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('local_interface_id', sa.BigInteger(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('remote_hostname', sa.String(length=255), nullable=True),
    sa.Column('remote_port', sa.String(length=255), nullable=True),
    sa.Column('remote_mgmt_address', postgresql.INET(), nullable=True),
    sa.Column('remote_platform', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['local_interface_id'], ['interfaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_neighbors_device_id', 'neighbors', ['device_id'], unique=False)
    op.create_index('ix_neighbors_local_interface_id', 'neighbors', ['local_interface_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_neighbors_local_interface_id', table_name='neighbors')
    op.drop_index('ix_neighbors_device_id', table_name='neighbors')
    op.drop_table('neighbors')
    op.drop_index('ix_interface_metrics_recorded_at', table_name='interface_metrics')
    op.drop_index('ix_interface_metrics_interface_id', table_name='interface_metrics')
    op.drop_table('interface_metrics')
    op.drop_index('ix_job_runs_status', table_name='job_runs')
    op.drop_index('ix_job_runs_started_at', table_name='job_runs')
    op.drop_index('ix_job_runs_device_id', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_interfaces_device_id', table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_table('device_credentials')
    op.drop_index('ix_device_capabilities_device_id', table_name='device_capabilities')
    op.drop_index('ix_device_capabilities_capability_id', table_name='device_capabilities')
    op.drop_table('device_capabilities')
    op.drop_index('ix_devices_vendor_id', table_name='devices')
    op.drop_index('ix_devices_raw_facts', table_name='devices', postgresql_using='gin')
    op.drop_index('ix_devices_management_ip', table_name='devices')
    op.drop_index('ix_devices_is_active', table_name='devices')
    op.drop_index('ix_devices_device_type_id', table_name='devices')
    op.drop_table('devices')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('device_types')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
